#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2017 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. ${TOP_SRCDIR}/tests/scripts/defines.sh

if test "$BACKEND" != "bdb" && test "$BACKEND" != "hdb" ; then
	echo "Warning: this test is known to affect bdb and hdb, although it may impact other backends as well."
fi

mkdir -p $DBDIR1A $DBDIR2A

ITS=4184
ITSDIR=$DATADIR/regressions/its$ITS
USER="uid=user1,ou=People,dc=example,dc=com"
PASS="abc"

echo "Running slapadd to build slapd database..."
config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd.conf > $CONF1
$SLAPADD -f $CONF1 -l $ITSDIR/adds.ldif
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

echo ""
echo "	This test applies a round of updates __after__ grabbing a lock"
echo "	that, before the fix, was not correctly released; in case "
echo "	of failure, the second round of updates will deadlock."
echo "	This issue was fixed in OpenLDAP 2.3.14."
echo ""

for S in 1 2 ; do
	FILE="${ITSDIR}/mods.ldif"
	echo "${S}) Applying `basename ${FILE}`..."
	$LDAPMODIFY -v -D "$USER" -w $PASS -h $LOCALHOST -p $PORT1 \
		-f "${FILE}" > $TESTOUT 2>&1
	RC=$?
	if test $RC != 0 ; then
		echo "ldapmodify failed ($RC)!"
		killservers
		exit $RC
	fi
	sleep 1
done

killservers
echo ">>>>> Test succeeded"
exit 0
