.TH SLAPTEST 8C "RELEASEDATE" "OpenLDAP LDVERSION"
.\" Copyright 2004-2014 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.\" $OpenLDAP$
.SH НАЗВАНИЕ
slaptest \- проверка правильности конфигурации демона slapd OpenLDAP
.SH СИНТАКСИС
.B SBINDIR/slaptest
[\c
.BI \-d \ debug-level\fR]
[\c
.BI \-f \ slapd.conf\fR]
[\c
.BI \-F \ confdir\fR]
[\c
.BI \-n dbnum\fR]
[\c
.BI \-o \ option\fR[ = value\fR]]
[\c
.BR \-Q ]
[\c
.BR \-u ]
[\c
.BR \-v ]
.LP
.SH ОПИСАНИЕ
.LP
.B slaptest
используется для проверки соответствия конфигурации
.BR slapd (8).
Утилита открывает конфигурационный файл
.BR slapd.conf (5)
или базу данных
.BR slapd\-config (5)
и анализирует их в соответствии с общими правилами и правилами, специфичными для
механизмов манипуляции данными, проверяя корректность их составления.
.LP
.SH ПАРАМЕТРЫ
.TP
.BI \-d \ debug-level
Включает вывод отладочных сообщений в соответствии с указанным уровнем
.IR debug-level ;
подробнее смотрите в
.BR slapd (8).
.TP
.BI \-f \ slapd.conf
Определяет альтернативный файл
.BR slapd.conf (5).
.TP
.BI \-F \ confdir
Определяет конфигурационную директорию.
Если указаны сразу и
.B \-f
и
.BR \-F ,
конфигурационный файл будет прочтён, переконвертирован в формат
конфигурационной директории и записан в указанную директорию.
Если не указан ни один из этих параметров, slaptest
попытается прочитать конфигурационную директорию по умолчанию,
а затем использовать конфигурационный файл по умолчанию.
Если существует конфигурационная директория в правильном формате,
то конфигурационный файл игнорируется.
Если при этом указан режим холостого прогона, конвертация произведена не будет.
.TP
.BI \-n \ dbnum
Открыть и протестировать только базу данных с порядковым номером
\fIdbnum\fR из перечисленных в конфигурационном файле. Чтобы
протестировать только конфигурационную базу данных
.BR slapd\-config (5),
используйте
.BR \-n\ 0 ,
поскольку эта база данных всегда является первой.
.TP
.BI \-o \ option\fR[ = value\fR]
Определяет опцию
.I option
с необязательным значением
.IR value .
Возможные опции/значения общего назначения:
.LP
.nf
              syslog=<subsystems>  (смотрите `\-s' в slapd(8))
              syslog\-level=<level> (смотрите `\-S' в slapd(8))
              syslog\-user=<user>   (смотрите `\-l' в slapd(8))

.fi
.TP
.BI \-Q
Определяет экстремально "тихий" режим: выдается только код возврата, показывающий
успешное (0) или неуспешное (любое другое значение) завершение работы.
.TP
.B \-u
Включает режим холостого прогона (то есть не будет выдаваться ошибок,
если невозможно открыть базу данных, но конфигурация в порядке).
.TP
.B \-v
Включает режим подробного вывода.
.SH ПРИМЕРЫ
Для проверки
.BR slapd.conf (5)
выполните команду:
.LP
.nf
.ft tt
	SBINDIR/slaptest \-f ETCDIR/slapd.conf \-v
.ft
.fi
.SH "СМОТРИТЕ ТАКЖЕ"
.BR ldap (3),
.BR slapd (8),
.BR slapdn (8)
.LP
"Руководство администратора OpenLDAP" (http://www.OpenLDAP.org/doc/admin/, http://pro-ldap.ru/tr/admin24/).
.SH "ПРИЗНАНИЕ ЗАСЛУГ"
.so ../Project
