.lf 1 stdin
.TH SLAPD-MDB 5 "2014/09/20" "OpenLDAP 2.4.40"
.\" Copyright 2011-2014 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.\" $OpenLDAP$
.SH НАЗВАНИЕ
slapd\-mdb \- механизм манипуляции данными для slapd Memory-Mapped DB (отображаемая в памяти база данных)
.SH СИНТАКСИС
.B /usr/local/etc/openldap/slapd.conf
.SH ОПИСАНИЕ
Механизм манипуляции данными для
.BR slapd (8)
\fBmdb\fP использует для хранения данных библиотеку OpenLDAP Lightning Memory-Mapped DB (LMDB).
В вопросах управления памятью эта библиотека полностью полагается на операционную систему,
в которой она выполняется, и не использует собственных механизмов кэширования.
\fBmdb\fP является рекомендуемым первичным механизмом для работы с базами данных.
.LP
Механизм \fBmdb\fP похож на механизм \fBhdb\fP в том, что он использует иерархическое
представление базы данных с поддержкой переименования поддеревьев. Этот механизм более компактен
и более производителен, чем \fBbdb\fP, и в то же время он гораздо проще настраивается.
.SH КОНФИГУРАЦИЯ
Приведённые ниже директивы
.B slapd.conf
применяются к базам данных механизма манипуляции данными \fBmdb\fP.
То есть они должны следовать за строкой "database mdb" и находиться до последующих строк
"backend" или "database". Другие относящиеся к базам данных директивы описаны в man-странице
.BR slapd.conf (5).
.TP
.BI checkpoint \ <kbyte>\ <min>
Указывает частоту синхронизации дисковых буферов базы данных.
Эта установка требуется лишь при использовании директивы \fBdbnosync\fP.
Выгрузка данных произойдёт либо при записи данных размером \fI<kbyte>\fP Кбайт,
либо по прошествии \fI<min>\fP минут с момента последней выгрузки.
По умолчанию оба аргумента установлены в ноль, в этом случае они игнорируются. Если аргумент
\fI<min>\fP отличен от нуля, каждые \fI<min>\fP минут будет запускаться внутренняя задача по выгрузке данных.
Примечание: в настоящее время обработка установки \fI<kbyte>\fP не реализована.
.TP
.B dbnosync
Указывает, что содержимое базы данных на диске не должно немедленно синхронизироваться
при изменении содержимого базы данных в памяти. Включение этой опции может повысить
производительность за счёт увеличения риска потери данных. В частности, если до синхронизации
изменений произойдёт крах операционной системы, некоторое количество транзакций может быть потеряно.
По умолчанию при фиксации каждой транзакции выполняется полная синхронизация данных.
.TP
.BI directory \ <directory>
Указывает директорию, где находятся LMDB-файлы, содержащие эту базу данных и ассоциированные с ней индексы.
Для каждой базы данных должна быть определена отдельная директория. По умолчанию -
.BR /usr/local/var/openldap\-data .
.TP
\fBenvflags \fR{\fBnosync\fR,\fBnometasync\fR,\fBwritemap\fR,\fBmapasync\fR,\fBnordahead\fR}
Указывает флаги для более детального контроля работы библиотеки LMDB.
.RS
.TP
.B nosync
То же самое, что и директива
.IR dbnosync .
.RE
.RS
.TP
.B nometasync
При фиксации транзакции данные синхронизируются, а синхронизация метастраницы пропускается.
Этот метод несколько быстрее, чем выполнение полной синхронизации, но существует вероятность потери
последних зафиксированных транзакций при крахе операционной системы. Если выставлены оба флага
.I nometasync
и
.IR nosync ,
приоритет будет у флага
.IR nosync .
.RE
.RS
.TP
.B writemap
Использовать отображение в памяти с возможностью записи, а не в режиме "только чтение".
Это ускоряет операции записи, но может привести к разрушению базы данных в случае какой-либо ошибки в slapd,
приводящей к случайным записям в область mmap.
.RE
.RS
.TP
.B mapasync
При использовании отображения в памяти с возможностью записи и выполнении синхронизации
при каждой фиксации транзакции, применять асинхронную синхронизацию вместо синхронной (по умолчанию).
Эта опция не имеет никакого эффекта, если флаг
.I writemap
не установлен. Также она не будет иметь эффекта, если установлен флаг
.IR nosync .
.RE
.RS
.TP
.B nordahead
Отключает упреждающее чтение файла. Обычно операционная система выполняет упреждающее чтение при каждом запросе на чтение.
Как правило, это повышает производительность операций чтения, но может ухудшить производительность при чтении
с произвольным доступом, если системная память заполнена и размер базы данных больше чем объём RAM.
Эта опция не реализована на Windows.
.RE

.TP
\fBindex \fR{\fI<attrlist>\fR|\fBdefault\fR} [\fBpres\fR,\fBeq\fR,\fBapprox\fR,\fBsub\fR,\fI<special>\fR]
Указывает индексы, которые поддерживаются для указанного атрибута (или списка атрибутов).
Некоторые атрибуты поддерживают не все индексы.
Если задан только список атрибутов \fI<attrlist>\fP, для этих атрибутов будут поддерживаться индексы,
указанные как индексы по умолчанию \fBdefault\fR. Обратите внимание, что задание индексов по умолчанию
не подразумевает, что будут проиндексированы все атрибуты. Кроме того, для лучшей производительности, для атрибута
.B objectClass
следует всегда настраивать индекс
.BR eq .

Может быть указано несколько специальных параметров индексирования. Тип индекса
.B sub
может быть представлен как три отдельных типа
.BR subinitial ,
.B subany
и
.BR subfinal .
Для запрета использования данного индекса для языковых подтипов может быть указан специальный тип
.BR nolang .
Для запрета использования данного индекса для именованных подтипов может быть указан специальный тип
.BR nosubtypes .
Примечание: при изменении установок \fBindex\fP в
.BR slapd.conf (5)
требуется повторное построение индексов, смотрите
.BR slapindex (8);
динамическое изменение установок \fBindex\fP путём выполнения операций LDAPModifying над "cn=config"
приводит к автоматическому онлайн-перепостроению индексов в фоновом режиме.
.TP
.BI maxreaders \ <integer>
Указывает максимальное количество потоков, которые могут параллельно получать доступ на чтение к базе данных.
Работа таких инструментов, как slapcat считается за один поток в дополнение к потокам
в любых активных процессах slapd. Значение по умолчанию - 126.
.TP
.BI maxsize \ <bytes>
Указывает максимальный размер базы данных в байтах. При запуске под отображение базы данных в памяти
выделяется соответствующее количество памяти, и базе данных не будет позволено выйти за пределы этого размера.
Значение по умолчанию - 10485760 байт. Эту настройку можно изменить, если установленный предел требуется увеличить.

Примечание: Важно установить значение этой директивы как можно большим
(с учётом ожидаемого реального прироста базы данных с течением времени),
поскольку последующее увеличение размера может оказаться неосуществимым при высокой загрузке системы.
.TP
.BI mode \ <integer>
Указывает режим защиты файлов (права на доступ к ним), который следует назначать вновь создаваемым файлам базы данных.
Значение по умолчанию - 0600.
.TP
.BI searchstack \ <depth>
Указывает глубину стека, используемого для оценки поискового фильтра.
Оценка поисковых фильтров происходит по стеку, в который помещаются вложенные условия AND / OR.
Для каждого потока сервера выделяется собственный стек. Глубина стека определяет,
насколько комплексные фильтры могут быть оценены без необходимости выделения дополнительной памяти.
Применение поискового фильтра с глубиной вложенности большей, чем глубина поискового стека,
приведёт к тому, что для этой конкретной операции поиска будет выделен отдельный стек.
Подобные выделения могут оказать существенное негативное влияние на производительность сервера,
но и определение слишком большого стека также приведёт к потреблению большого объёма памяти.
Каждый поисковый стек использует 512 Kb для одного вложенного уровня условий.
Глубина стека по умолчанию - 16, то есть используется 8 Mb памяти для каждого потока.
.SH КОНТРОЛЬ ДОСТУПА
Механизм манипуляции данными
.B mdb
соблюдает указанные в
.BR slapd.access (5)
семантики контроля доступа.
.SH ФАЙЛЫ
.TP
.B /usr/local/etc/openldap/slapd.conf
конфигурационный файл
.B slapd
по умолчанию.
.SH СМОТРИТЕ ТАКЖЕ
.BR slapd.conf (5),
.BR slapd\-config (5),
.BR slapd (8),
.BR slapadd (8),
.BR slapcat (8),
.BR slapindex (8),
документацию LMDB OpenLDAP.
.SH ПРИЗНАНИЕ ЗАСЛУГ
.lf 1 ./../Project
.\" Shared Project Acknowledgement Text
.B "Программное обеспечение OpenLDAP"
разработано и поддерживается проектом OpenLDAP <http://www.openldap.org/>.
.B "Программное обеспечение OpenLDAP"
является производным от релиза 3.3 LDAP Мичиганского Университета.
.lf 198 stdin
Автор man-страницы - Howard Chu.
