#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2018 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. ${TOP_SRCDIR}/tests/scripts/defines.sh

if test ${AC_conf[ldap]} = no ; then
	echo "LDAP backend not available, test skipped"
	exit 0
fi

mkdir -p $TESTDIR $DBDIR1 $DBDIR2

ITS=4326
ITSDIR=$DATADIR/regressions/its$ITS

echo "Running slapadd to build slapd database..."
config_filter $BACKEND ${AC_conf[monitor]} < $CONF > $CONF1
$SLAPADD -f $CONF1 -l $LDIFORDERED
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
SERVERPID=$!
if test $WAIT != 0 ; then
    echo SERVERPID $SERVERPID
    read foo
fi
KILLPIDS="$SERVERPID"
check_running 1

echo "Starting proxy slapd on TCP/IP port $PORT2..."
config_filter $BACKEND ${AC_conf[monitor]} < $ITSDIR/slapd.conf > $CONF2
$SLAPD -f $CONF2 -h $URI2 $TIMING > $LOG2 2>&1 &
PROXYPID=$!
if test $WAIT != 0 ; then
    echo PROXYPID $PROXYPID
    read foo
fi
KILLPIDS="$KILLPIDS $PROXYPID"
check_running 2

echo "Searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

echo "Re-searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

SLEEP=2
echo "Stopping the server and sleeping $SLEEP seconds..."
kill -HUP "$SERVERPID"
wait $SERVERPID
sleep $SLEEP
KILLPIDS="$PROXYPID"

echo "Searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
case $RC in
0)
	echo "ldapsearch should have failed ($RC)!"
	killservers
	exit $RC
	;;
52)
	echo "ldapsearch failed ($RC)"
	;;
*)
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
	;;
esac

echo "Re-searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
case $RC in
0)
	echo "ldapsearch should have failed ($RC)!"
	killservers
	exit $RC
	;;
52)
	echo "ldapsearch failed ($RC)"
	;;
*)
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
	;;
esac

echo "Restarting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
SERVERPID=$!
if test $WAIT != 0 ; then
    echo SERVERPID $SERVERPID
    read foo
fi
KILLPIDS="$SERVERPID $PROXYPID"
check_running 1

echo "Searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

echo "Re-searching the proxy..."
$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
	'(objectClass=*)' > /dev/null 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

killservers
echo ">>>>> Test succeeded"
exit 0
