#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2016 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

mkdir -p $TESTDIR $DBDIR1A $DBDIR1B $DBDIR1C
ITS=6794
ITSDIR=$DATADIR/regressions/its$ITS
ITSCONF=$ITSDIR/slapd-glue.conf

echo "Running multi-threaded slapadd in quick mode to build glued slapd databases..."
config_filter $BACKEND ${AC_conf[monitor]} < $ITSCONF > $CONF1
$SLAPADD -q -f $CONF1 -l $LDIFORDERED > $SLAPADDLOG1 2>&1
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 > $SEARCHOUT 2>&1
RC=$?

killservers

if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	exit $RC
fi

echo "Filtering ldapsearch results..."
$LDIFFILTER -s ldif=e < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER -s ldif=e < $LDIFGLUED > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "comparison failed - database was not created correctly"
	echo $SEARCHFLT $LDIFFLT
	$DIFF $SEARCHFLT $LDIFFLT
	exit 1
fi

echo ">>>>> Test succeeded"
exit 0
