#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2016 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "#######################################################################"
echo "###                                                                 ###"
echo "### regression tests                                                ###"
echo "###                                                                 ###"
echo "#######################################################################"
echo "###"

. ${TOP_SRCDIR}/tests/scripts/defines.sh

if [ -n "$CIBUZZ_PID4" -o -n "$RANDOM_ORDER" ]; then
	TEST_LIST_CMD=$(ls ${TOP_SRCDIR}/tests/data/regressions/its*/its* | sort --random-sort)
else
	TEST_LIST_CMD=${TOP_SRCDIR}/tests/data/regressions/its*/its*
fi

TESTSET='all LDAP ITS regression tests'

run_testset
