#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2016 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

. ${TOP_SRCDIR}/tests/scripts/defines.sh

teamcity_msg "testSuiteStarted name='all LDAP ITS regression tests'"

echo "#######################################################################"
echo "###                                                                 ###"
echo "### regression tests                                                ###"
echo "###                                                                 ###"
echo "#######################################################################"
echo "###"

echo ">>>>> Executing all LDAP ITS regression tests"

for CMD in ${TOP_SRCDIR}/tests/data/regressions/its*/its*; do
	# remove cruft from prior test
	if test $PRESERVE = yes ; then
		/bin/rm -rf testrun/db.*
	else
		/bin/rm -rf testrun
	fi

	teamcity_msg "testStarted name='`basename $CMD`' captureStandardOutput='true'"
	echo ">>>>> Starting ${TB}`basename $CMD`${TN} ..."
	$CMD
	RC=$?
	if test $RC -eq 0 ; then
		echo ">>>>> $CMD completed ${TB}OK${TN}."
	else
		echo ">>>>> $CMD ${TB}failed${TN} (exit $RC)"
		teamcity_msg "testFailed name='`basename $CMD`'"
		exit $RC
	fi

	echo ""
	teamcity_msg "testFinished name='`basename $CMD`'"
done

teamcity_msg "testSuiteFinished name='all LDAP ITS regression tests'"
