#!/bin/bash
## $ReOpenLDAP$
## Copyright (c) 2015,2016 Leonid Yuriev <leo@yuriev.ru>.
## Copyright (c) 2015,2016 Peter-Service R&D LLC <http://billing.ru/>.
##
## This file is part of ReOpenLDAP.
##
## ReOpenLDAP is free software; you can redistribute it and/or modify it under
## the terms of the GNU Affero General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## ReOpenLDAP is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ---
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

if test $# -eq 0 ; then
	test -z "$SRCDIR" && SRCDIR="."
else
	SRCDIR=$1; shift
fi
if test $# -eq 1 ; then
	BACKEND=$1; shift
fi

echo "running defines.sh $SRCDIR $BACKEND"
. ${TOP_SRCDIR}/tests/scripts/defines.sh

if test -d "$TESTDIR"; then
	echo "Cleaning up in $TESTDIR..."
	/bin/rm -rf $TESTDIR/db.*
fi
mkdir -p $TESTDIR

echo "Starting slapd on TCP/IP port $PORT1..."
config_filter $BACKEND ${AC_conf[monitor]} < $PASSWDCONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test ${WAIT-0} != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

cat /dev/null > $TESTOUT

echo "Testing base suffix searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -s base -h $LOCALHOST -p $PORT1 \
	'(objectclass=*)' >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	killservers
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing user searching..."
$LDAPSEARCH -L -S "" -b "uid=root,$BASEDN" -s base -h $LOCALHOST -p $PORT1 \
	'(objectclass=*)' >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	killservers
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing exact searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(uid=root)' >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	killservers
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing OR searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(|(objectclass=person)(cn=root))' >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	killservers
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing AND searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(&(objectclass=person)(cn=root))' >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	killservers
	exit $RC
fi

killservers

echo "Assuming everything is fine (o-o ;)."
#echo "Comparing results"
#$CMP $TESTOUT $SEARCHOUTMASTER
#if test $? != 0 ; then
#	echo "Comparison failed"
#	exit 1
#fi

echo ">>>>> Test succeeded"
exit 0
