#!/bin/bash
## $ReOpenLDAP$
## Copyright 1998-2018 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. ${TOP_SRCDIR}/tests/scripts/defines.sh

mkdir -p $TESTDIR $DBDIR2

echo "Starting slapd on TCP/IP port $PORT2..."
config_filter $BACKEND < $CONFTWO > $CONF2
$SLAPD -f $CONF2 -h $URI2 $TIMING > /dev/null 2>&1 &
PID=$!
sleep 0.1

echo "Using ldapsearch to retrieve all the entries..."
for i in 1 2 3 4 5; do
	$LDAPSEARCH -S "" -b "" -s base -h $LOCALHOST -p $PORT2 > $SERVER2OUT 2>&1
	RC=$?
	if test $RC = 1 ; then
		echo "Waiting $i seconds for slapd to start..."
		sleep $i
	fi
done

if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	exit $RC
fi

echo ">>>>> Server2 (pid=$PID) started"
exit 0
