#!/bin/bash
# $OpenLDAP$
## This work is part of OpenLDAP Software <http://www.openldap.org/>.
##
## Copyright 1998-2015 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

mkdir -p $TESTDIR $DBDIR1

echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $PWCONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

echo "Using ldapadd to populate the database..."
$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD < \
	$LDIFPASSWD > $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo > $SEARCHOUT
echo > $TESTOUT

echo "Using ldapsearch to verify population ..."
echo "++ Initial search" >> $SEARCHOUT
$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
	-D "$MANAGERDN" -w $PASSWD \
	-b "$BASEDN" \
	'objectclass=*' >> $SEARCHOUT 2>&1

echo "Using ldappasswd to test a few error conditions ..."
echo "Pass 0" >> $TESTOUT
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -a "" -s newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC = 0 ; then
	echo "ldappasswd unexpectantly passed ($RC)! old empty"
	killservers
	exit 1
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -a oldsecret -s "" \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC = 0 ; then
	echo "ldappasswd unexpectantly passed ($RC)! new empty"
	killservers
	exit 1
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -a oldsecret -s newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC = 0 ; then
	echo "ldappasswd unexpectantly passed ($RC)! wrong old"
	killservers
	exit 1
fi

echo "Using ldappasswd (PASS 1)  ..."
echo "Pass 1" >> $TESTOUT
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -s newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w $PASSWD -s newsecret \
	-D "$MANAGERDN" "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -s newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w secret -s newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi

echo "" >> $TESTOUT
echo "Pass 2" >> $TESTOUT
echo "Using ldappasswd (PASS 2)  ..."
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w newsecret \
	-D "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT1 \
	-w newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Logging end state with ldapsearch..."
echo "" >> $TESTOUT
echo "++ End search" >> $TESTOUT
$LDAPSEARCH -h $LOCALHOST -p $PORT1 \
	-D "$MANAGERDN" -w $PASSWD \
	-b "$BASEDN" \
	'objectclass=*' >> $TESTOUT 2>&1


killservers
echo ">>>>> Test succeeded"
exit 0
