#!/bin/bash
## $ReOpenLDAP$
## Copyright 2004-2016 ReOpenLDAP AUTHORS: please see AUTHORS file.
## All rights reserved.
##
## This file is part of ReOpenLDAP.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. ${TOP_SRCDIR}/tests/scripts/defines.sh

mkdir -p $TESTDIR $DBDIR1 $DBDIR2

config_filter $BACKEND ${AC_conf[monitor]} < $EMPTYDNCONF > $CONF1

echo "Running slapadd to build \"dc=example,dc=com\" slapd database..."
$SLAPADD -f $CONF1 -n 1 -l $LDIFEMPTYDN1
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Running slapadd to build empty DN slapd database..."
$SLAPADD -f $CONF1 -b "" -l $LDIFEMPTYDN2
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

echo "Testing slapd empty DN handling..."

echo "Searching database..."

$LDAPSEARCH -S "" -b "" -h $LOCALHOST -p $PORT1 > $SEARCHOUT 2>&1

RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

kill -HUP $KILLPIDS
wait

echo "Filtering ldapsearch results..."
$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering expected results..."
$LDIFFILTER < $EMPTYDNOUT1 > $LDIFFLT
echo "Comparing ldapsearch results against original..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "comparison failed - empty DN write operations did not complete correctly"
	exit 1
fi

echo "Comparison of database generated via slapadd succeeded"

echo "Cleaning up database directories..."
/bin/rm -rf $TESTDIR/db.*

mkdir -p $TESTDIR $DBDIR1 $DBDIR2

echo "Starting slapd on TCP/IP port $PORT1..."
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"

echo "Testing slapd empty DN handling..."
for i in $SLEEP0 0.5 1 2 3 4 5 5; do
	echo "Waiting $i seconds for slapd to start..."
	sleep $i
	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
done

if test $RC != 0 ; then
	echo "ldapsearch failed! ($RC, $(date --rfc-3339=ns))"
	killservers
	exit $RC
fi

echo "Loading database..."
$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	-f $LDIFEMPTYDN1 > /dev/null 2>&1
$LDAPADD -D "$EMPTYDNDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	-f $LDIFEMPTYDN2 > /dev/null 2>&1

$LDAPMODIFY -D "$EMPTYDNDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	> /dev/null 2>&1 << EOF
dn: o=Beispiel,c=DE
changetype: delete

dn: c=DE
changetype: delete
EOF

echo "Searching database..."

$LDAPSEARCH -S "" -b "" -h $LOCALHOST -p $PORT1 > $SEARCHOUT 2>&1

RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

killservers

echo "Filtering ldapsearch results..."
$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering expected results..."
$LDIFFILTER < $EMPTYDNOUT2 > $LDIFFLT
echo "Comparing ldapsearch results against original..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "comparison failed - empty DN write operations did not complete correctly"
	exit 1
fi

#####

echo ">>>>> Test succeeded"
exit 0
