#!/bin/bash
# $ReOpenLDAP$
## Copyright (c) 2015,2016 Leonid Yuriev <leo@yuriev.ru>.
## Copyright (c) 2015,2016 Peter-Service R&D LLC <http://billing.ru/>.
##
## This file is part of ReOpenLDAP.
##
## ReOpenLDAP is free software; you can redistribute it and/or modify it under
## the terms of the GNU Affero General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## ReOpenLDAP is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ---
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo "### This test requires the LDAP backend and the rwm overlay."
echo "### If available, and explicitly requested, it can use SASL bind;"
echo "### note that SASL must be properly set up, and the requested"
echo "### mechanism must be available.  Define SLAPD_USE_SASL={yes|<mech>},"
echo "### with \"yes\" defaulting to DIGEST-MD5 to enable SASL authc[/authz]."

if test $BACKLDAP = "ldapno" ; then
	echo "LDAP backend not available, test skipped"
	exit 0
fi

if test $RWM = "rwmno" ; then
	echo "Rewrite/remap overlay not available, test skipped"
	exit 0
fi

if test $THREADS = "threadsno" ; then
	echo "Need threads support, test skipped"
	exit 0
fi

if test $WITH_SASL = "yes" ; then
	if test $USE_SASL != "no" ; then
		if test $USE_SASL = "yes" ; then
			MECH="DIGEST-MD5"
		else
			MECH="$USE_SASL"
		fi
		echo "Using SASL authc[/authz] with mech=$MECH; unset SLAPD_USE_SASL to disable"
	else
		echo "Using proxyAuthz with simple authc..."
	fi
else
	echo "SASL not available; using proxyAuthz with simple authc..."
fi

mkdir -p $TESTDIR $DBDIR1 $DBDIR2

echo "Running slapadd to build slapd database..."
. $CONFFILTER $BACKEND $MONITORDB < $IDASSERTCONF > $ADDCONF
$SLAPADD -f $ADDCONF -l $LDIFIDASSERT1 -n 1
RC=$?
if test $RC != 0 ; then
	echo "slapadd -n 1 failed ($RC)!"
	exit $RC
fi
$SLAPADD -f $ADDCONF -l $LDIFIDASSERT2 -n 2
RC=$?
if test $RC != 0 ; then
	echo "slapadd -n 2 failed ($RC)!"
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT..."
. $CONFFILTER $BACKEND $MONITORDB < $IDASSERTCONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

echo "Testing ldapwhoami as proxy US..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy US,ou=Admin,dc=example,dc=com" -w proxy
RC=$?
if test $RC != 0 ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

AUTHZID="u:it/jaj"
echo "Testing ldapwhoami as proxy US, $AUTHZID..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy US,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 0 && test $BACKEND != null ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

AUTHZID="u:bjorn"
echo "Testing ldapwhoami as proxy US, $AUTHZID... (should fail)"
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy US,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 1 ; then
	echo "ldapwhoami should have failed ($RC)!"
	killservers
	exit 1
fi

AUTHZID="u:bjensen"
echo "Testing ldapwhoami as proxy US, $AUTHZID... (should fail)"
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy US,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 1 ; then
	echo "ldapwhoami should have failed ($RC)!"
	killservers
	exit 1
fi

echo "Testing ldapwhoami as proxy IT..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy IT,ou=Admin,dc=example,dc=com" -w proxy
RC=$?
if test $RC != 0 ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

AUTHZID="u:it/jaj"
echo "Testing ldapwhoami as proxy IT, $AUTHZID... (should fail)"
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy IT,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 1 ; then
	echo "ldapwhoami should have failed ($RC)!"
	killservers
	exit 1
fi

AUTHZID="u:bjorn"
echo "Testing ldapwhoami as proxy IT, $AUTHZID... (should fail)"
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy IT,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 1 ; then
	echo "ldapwhoami should have failed ($RC)!"
	killservers
	exit 1
fi

AUTHZID="dn:cn=Sandbox,ou=Admin,dc=example,dc=com"
echo "Testing ldapwhoami as proxy IT, $AUTHZID..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "cn=proxy IT,ou=Admin,dc=example,dc=com" -w proxy -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 0 && test $BACKEND != null ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

AUTHZID="dn:uid=bjorn,ou=People,o=Example,c=US"
echo "Testing ldapwhoami as bjorn, $AUTHZID..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "uid=bjorn,ou=people,dc=example,dc=com" -w bjorn -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 0 ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

AUTHZID="dn:uid=bjorn,ou=People,o=Esempio,c=IT"
echo "Testing ldapwhoami as bjorn, $AUTHZID..."
$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "uid=bjorn,ou=people,dc=example,dc=com" -w bjorn -e\!"authzid=$AUTHZID"
RC=$?
if test $RC != 0 ; then
	echo "ldapwhoami failed ($RC)!"
	killservers
	exit $RC
fi

ID="uid=jaj,ou=People,dc=example,dc=it"
BASE="o=Example,c=US"
echo "Testing ldapsearch as $ID for \"$BASE\"..."
$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASE" \
	-D "$ID" -w jaj > $SEARCHOUT 2>&1

RC=$?
if test $RC != 0 && test $BACKEND != null ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

echo "Filtering ldapsearch results..."
$LDIFFILTER -s ldif=e < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER -s ldif=e < $IDASSERTOUT > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "comparison failed - search with identity assertion didn't succeed"
	killservers
	exit 1
fi

if test $USE_SASL != "no" ; then
	ID="it/jaj"
	BASE="o=Example,c=US"
	echo "Testing ldapsearch as $ID for \"$BASE\" with SASL bind and identity assertion..."
	$LDAPSASLSEARCH -h $LOCALHOST -p $PORT1 -b "$BASE" \
		-Q -U "$ID" -w jaj -Y $MECH > $SEARCHOUT 2>&1

	RC=$?
	if test $RC != 0 ; then
		echo "ldapsearch failed ($RC)!"
		killservers
		exit $RC
	fi

	echo "Filtering ldapsearch results..."
	$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
	echo "Filtering original ldif used to create database..."
	$LDIFFILTER < $IDASSERTOUT > $LDIFFLT
	echo "Comparing filter output..."
	$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

	if test $? != 0 ; then
		echo "comparison failed - search with SASL bind and identity assertion didn't succeed"
		killservers
		exit 1
	fi
fi

killservers
echo ">>>>> Test succeeded"
exit 0
