#!/bin/bash
# $ReOpenLDAP$
## Copyright (c) 2015,2016 Leonid Yuriev <leo@yuriev.ru>.
## Copyright (c) 2015,2016 Peter-Service R&D LLC <http://billing.ru/>.
##
## This file is part of ReOpenLDAP.
##
## ReOpenLDAP is free software; you can redistribute it and/or modify it under
## the terms of the GNU Affero General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## ReOpenLDAP is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ---
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

if test $BACKEND = bdb ; then
	echo "subtree rename not supported by back-$BACKEND"
	exit 0
fi

mkdir -p $TESTDIR $DBDIR1

echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

cat /dev/null > $TESTOUT
cat /dev/null > $SEARCHOUT

# Add
echo "Populating the database..."
echo "# Populating the database..." >> $TESTOUT
$LDAPADD -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	>> $TESTOUT 2>&1 << EOMODS0
dn: dc=example,dc=com
objectClass: organization
objectClass: dcObject
o: Example, Inc.
dc: example

dn: ou=Parent,dc=example,dc=com
objectClass: organizationalUnit
ou: Parent

dn: ou=Another parent,dc=example,dc=com
objectClass: organizationalUnit
ou: Another parent

dn: ou=Child,ou=Parent,dc=example,dc=com
objectClass: organizationalUnit
ou: Child

dn: ou=Grandchild,ou=Child,ou=Parent,dc=example,dc=com
objectClass: organizationalUnit
ou: Grandchild
EOMODS0
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Searching all database..."
echo "# Searching all database (after add)..." >> $SEARCHOUT
$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(objectClass=*)' >> $SEARCHOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

# Rename (PASS1)
echo "Renaming (PASS1)..."
echo "# Renaming (PASS1)..." >> $TESTOUT
$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	>> $TESTOUT 2>&1 << EOMODS1
dn: ou=Child,ou=Parent,dc=example,dc=com
changetype: modrdn
newrdn: ou=Renamed child
deleteoldrdn: 0
EOMODS1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Searching all database..."
echo "# Searching all database (after PASS1)..." >> $SEARCHOUT
$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(objectClass=*)' >> $SEARCHOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

# Rename (PASS2)
echo "Renaming (PASS2)..."
echo "# Renaming (PASS2)..." >> $TESTOUT
$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	>> $TESTOUT 2>&1 << EOMODS2
dn: ou=Parent,dc=example,dc=com
changetype: modrdn
newrdn: ou=Renamed parent
deleteoldrdn: 0
EOMODS2
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Searching all database..."
echo "# Searching all database (after PASS2)..." >> $SEARCHOUT
$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(objectClass=*)' >> $SEARCHOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

# Rename (PASS3)
echo "Renaming (PASS3)..."
echo "# Renaming (PASS3)..." >> $TESTOUT
$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
	>> $TESTOUT 2>&1 << EOMODS3
dn: ou=Renamed child,ou=Renamed parent,dc=example,dc=com
changetype: modrdn
newrdn: ou=Renamed child
deleteoldrdn: 0
newsuperior: ou=Another parent,dc=example,dc=com
EOMODS3
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Searching all database..."
echo "# Searching all database (after PASS3)..." >> $SEARCHOUT
$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
	'(objectClass=*)' >> $SEARCHOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	killservers
	exit $RC
fi

killservers

LDIF=$SUBTREERENAMEOUT

echo "Filtering ldapsearch results..."
$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER < $LDIF > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "Comparison failed"
	exit 1
fi

echo ">>>>> Test succeeded"
exit 0
