#!/bin/bash
# $ReOpenLDAP$
## Copyright (c) 2015,2016 Leonid Yuriev <leo@yuriev.ru>.
## Copyright (c) 2015,2016 Peter-Service R&D LLC <http://billing.ru/>.
##
## This file is part of ReOpenLDAP.
##
## ReOpenLDAP is free software; you can redistribute it and/or modify it under
## the terms of the GNU Affero General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## ReOpenLDAP is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ---
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo ""

if test $BACKLDAP = ldapno ; then
	echo "ldap backend not available, test skipped"
	exit 0
fi

if test $RWM = rwmno ; then
	echo "rwm (rewrite/remap) overlay not available, test skipped"
	exit 0
fi

if test x$TESTLOOPS = x ; then
	TESTLOOPS=50
fi

if test x$TESTOLOOPS = x ; then
	TESTOLOOPS=1
fi

if test x$TESTCHILDREN = x ; then
	TESTCHILDREN=20
fi

mkdir -p $TESTDIR $DBDIR1 $DBDIR2

echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $METACONF1 > $CONF1
echo " = $SLAPD_HUGE -f $CONF1 -h $URI1 $TIMING"
$SLAPD_HUGE -f $CONF1 -h $URI1 $TIMING |& gzip > $LOG1.gz &
PID=$(jobs -p | tail -1)
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1 first

echo "Using ldapadd to populate the database..."
$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD < \
	$LDIFORDERED > $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT2..."
. $CONFFILTER $BACKEND $MONITORDB < $METACONF2 > $CONF2
echo " = $SLAPD_HUGE -f $CONF2 -h $URI2 $TIMING"
$SLAPD_HUGE -f $CONF2 -h $URI2 $TIMING |& gzip > $LOG2.gz &
PID=$(jobs -p | tail -1)
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$KILLPIDS $PID"
check_running 2 second

echo "Using ldapadd to populate the database..."
$LDAPADD -D "$METAMANAGERDN" -h $LOCALHOST -p $PORT2 -w $PASSWD < \
	$LDIFMETA >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	killservers
	exit $RC
fi

echo "Starting slapd on TCP/IP port $PORT3..."
. $CONFFILTER $BACKEND $MONITORDB < $GLUELDAPCONF > $CONF3
echo " = $SLAPD_HUGE -f $CONF3 -h $URI3 $TIMING"
$SLAPD_HUGE -f $CONF3 -h $URI3 $TIMING |& gzip > $LOG3.gz &
PID=$(jobs -p | tail -1)
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$KILLPIDS $PID"
check_running 3 thrid

cat /dev/null > $SEARCHOUT

mkdir -p $TESTDIR/$DATADIR
METABASEDN="o=Example,c=US"
for f in $DATADIR/do_* ; do
	sed -e "s;$BASEDN;$METABASEDN;" $f > $TESTDIR/$f
done

# add a read that matches only the local database, but selects
# also the remote as candidate; this should be removed to compare
# execution times with test008...
for f in $TESTDIR/$DATADIR/do_read.* ; do
	echo "ou=Meta,$METABASEDN" >> $f
done

# add a read that matches a referral in the local database only,
# but selects also the remote as candidate; this should be removed
# to compare execution times with test008...
for f in $TESTDIR/$DATADIR/do_read.* ; do
	echo "cn=Somewhere,ou=Meta,$METABASEDN" >> $f
done

# add a bind that resolves to a referral
for f in $TESTDIR/$DATADIR/do_bind.* ; do
	echo "cn=Foo,ou=Meta,$METABASEDN" >> $f
	echo "bar" >> $f
	echo "" >> $f
	echo "" >> $f
done

# fix test data to include back-monitor, if available
# NOTE: copies do_* files from $TESTDIR/$DATADIR to $TESTDIR
$MONITORDATA "$MONITORDB" "$TESTDIR/$DATADIR" "$TESTDIR"

echo "Using tester for concurrent server access..."
BINDDN="cn=Manager,o=Local"
PASSWD="secret"
$SLAPDTESTER -P "$PROGDIR" -d "$TESTDIR" -h $LOCALHOST -p $PORT3 \
	-D "$BINDDN" -w $PASSWD \
	-l $TESTLOOPS -L $TESTOLOOPS -j $TESTCHILDREN -r 20 \
	-i '!REFERRAL' -i '*INVALID_CREDENTIALS' -SS
RC=$?

if test $RC != 0 ; then
	echo "slapd-tester failed ($RC)!"
	killservers
	exit $RC
fi

echo "Delay $SLEEP0 seconds to handle previous and closed connection(s)..."
sleep $SLEEP0

echo "Using ldapsearch to retrieve all the entries..."
$LDAPSEARCH -S "" -b "$METABASEDN" -h $LOCALHOST -p $PORT3 \
			'(objectClass=*)' > $SEARCHOUT 2>&1
RC=$?

killservers

if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	exit $RC
fi

echo "Filtering ldapsearch results..."
$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER < $METACONCURRENCYOUT > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "comparison failed - slapd-ldap search/modification didn't succeed"
	exit 1
fi

echo ">>>>> Test succeeded"
exit 0
