#!/bin/bash
# $ReOpenLDAP$
## Copyright (c) 2015,2016 Leonid Yuriev <leo@yuriev.ru>.
## Copyright (c) 2015,2016 Peter-Service R&D LLC <http://billing.ru/>.
##
## This file is part of ReOpenLDAP.
##
## ReOpenLDAP is free software; you can redistribute it and/or modify it under
## the terms of the GNU Affero General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## ReOpenLDAP is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ---
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

mkdir -p $TESTDIR $DBDIR1

echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"
check_running 1

echo "Using ldapsearch to retrieve the root DSE..."
$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT1 \
	'@extensibleObject' > $SEARCHOUT 2>&1
RC=$?

if test $RC = 0 ; then
	echo "Using ldapsearch to retrieve the cn=Subschema..."
	$LDAPSEARCH -b "cn=Subschema" -s base -h $LOCALHOST -p $PORT1 \
		'(&(objectClasses=top)(objectClasses=2.5.6.0))' cn objectClass \
		>> $SEARCHOUT  2>&1
	RC=$?

fi

count=2
if test $RC = 0 ; then
	case $MONITORDB in yes | mod)
		count=3
		echo "Using ldapsearch to retrieve the cn=Monitor..."
		$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT1 \
			'@monitor' >> $SEARCHOUT 2>&1
		RC=$?
		;;
	esac
fi

killservers

cat $SEARCHOUT


if test $RC != 0 ; then
	echo ">>>>> Test failed"
else
	RC=`grep '^dn:' $SEARCHOUT | wc -l`
	if test $RC != $count ; then
		echo ">>>>> Test failed: expected $count entries, got" $RC
		RC=1
	else
		echo ">>>>> Test succeeded"
		RC=0
	fi
fi

exit $RC
